/**
 * COPY dict landing v2: satu sumber kebenaran untuk semua string.
 * Bahasa UI = Indonesia (baku); EN menyertai. Aturan:
 * - Istilah SNI baku: "likuefaksi" (bukan "likuifaksi").
 * - Angka mengikuti skenario kurasi app (screenshot asli): 65 SEDANG,
 *   Vs30 450 m/s SC, PGA 0.42 g, FS 2.00, elevasi 94 mdpl.
 * - Tanpa gimmick jargon, tanpa overclaim AI, tanpa testimoni fiktif.
 */
export const COPY = {
  id: {
    /* ── Nav ── */
    navLayers: 'Di dalam app',
    navShowcase: 'Showcase',
    navValidation: 'Validasi',
    navMethod: 'Metodologi',
    navSources: 'Sumber Data',
    navFaq: 'FAQ',
    navLangGroup: 'Bahasa',
    navThemeToLight: 'Ganti ke mode terang',
    navThemeToDark: 'Ganti ke mode gelap',
    navCta: 'Mulai Analisis',

    /* ── Hero ── */
    heroBadgeTag: 'STANDAR SNI',
    heroBadge: 'Desk Study Geoteknik 1726:2019',
    heroBadgeLink: 'Lihat cara kerja',
    heroTitlePrefix: 'Cek risiko tanah properti',
    heroTitleItalic: 'cukup dari alamat',
    heroSub:
      'Ketik alamat properti Anda. S.A.F.E House menghitung risiko gempa, likuefaksi, dan banjir sesuai SNI 1726:2019 dari data resmi BNPB, PuSGeN, dan USGS. Gratis, tanpa akun, selesai dalam dua menit.',
    heroCTA: 'Analisis Gratis',
    heroKicker: 'Desk study geoteknik · SNI 1726:2019',
    heroFieldLabel: 'Alamat properti, koordinat, atau tautan Google Maps',
    heroFieldPlaceholder: 'Alamat properti atau koordinat',
    heroFieldSubmit: 'Analisis',
    heroFieldHint: 'Enter',
    heroReadoutIdle: 'Menunggu alamat',
    heroReadoutAddress: 'Alamat · pilih titik di peta',
    heroReadoutPreset: 'Lokasi contoh',
    heroReadoutCoord: 'Koordinat valid',
    heroReadoutInvalid: 'Koordinat di luar jangkauan',
    heroExamplesLabel: 'Contoh',
    heroDemoCta: 'Lihat contoh alamat',
    heroTrust: 'InaRISK BNPB · PuSGeN · BMKG · USGS · Open-Meteo · OpenStreetMap',
    heroWindowTitle: 'S.A.F.E House · /app · Bandar Lampung',
    heroAppAlt:
      'Mockup interaktif aplikasi S.A.F.E House: peta Bandar Lampung dengan titik audit, tombol jalankan audit, dan panel hasil skor 65 kategori SEDANG.',
    heroCaptionRoute: 'Rute /app · skenario kurasi Bandar Lampung',
    heroCaptionData: 'Data: sumber publik resmi · perhitungan deterministik',

    heroProof1: '5 bahaya dianalisis',
    heroProof2: 'Sumber data resmi tercantum',
    heroProof3: 'Siap lampiran PBG',

    /* ── Bento: Di dalam app ── */
    bentoEyebrow: 'Di dalam app',
    bentoTitle: 'Semua yang dibutuhkan, satu layar.',
    bentoLead:
      'Tanpa daftar fitur panjang. Ini yang terjadi setiap kali audit dijalankan.',
    bentoMapTitle: 'Peta & Lokasi Presisi.',
    bentoMapText: 'Tile resmi, resolusi tinggi, pin tepat di lokasi alamat properti yang dianalisis.',
    bentoInputTitle: 'Ketik alamat, langsung selesai.',
    bentoInputText: 'Cukup masukkan nama jalan, alamat rumah, atau lokasi proyek. Tanpa akun, tanpa instalasi.',
    bentoReportTitle: 'Laporan SNI.',
    bentoReportText: 'Parameter siap lampir dengan jejak sumber di tiap angka.',
    bentoPipelineTitle: 'Sepenuhnya otomatis.',
    bentoPipelineText: 'Tarik data, hitung, susun skor. Dua menit, bisa diulang.',
    bentoLayersTitle: 'Lima bahaya.',
    bentoLayersText: 'Gempa, likuefaksi, banjir, longsor, vulkanik dalam satu skor.',
    bentoCta: 'Buka app',

    /* ── Mockup interaktif /app ── */
    mockNavMap: 'Peta',
    mockNavResult: 'Hasil',
    mockNavReport: 'Laporan',
    mockLayersTitle: 'Lapisan bahaya',
    mockPointsTitle: 'Titik audit',
    mockPointsHint: 'Klik peta untuk audit titik baru.',
    mockKlikHint: 'Klik di mana saja untuk audit',
    mockLayerSeismic: 'Gempa',
    mockLayerLiquefaction: 'Likuefaksi',
    mockLayerFlood: 'Banjir',
    mockLayerLandslide: 'Longsor',
    mockLayerVolcanic: 'Vulkanik',
    mockCoordChip: '-5.4292, 105.2610',
    mockCityLabel: 'Bandar Lampung',
    mockBayLabel: 'Teluk Lampung',
    mockRunAudit: 'Jalankan Audit',
    mockRerun: 'Jalankan Ulang Audit',
    mockStep1: 'Menarik data resmi',
    mockStep2: 'Menghitung parameter SNI',
    mockStep3: 'Menyusun skor',
    mockScoreLabel: 'SKOR S.A.F.E',
    mockBandModerate: 'SEDANG',
    mockScoreNote: 'Layak dilanjutkan dengan catatan',
    mockMetricVs30: 'VS30',
    mockMetricVs30Sub: 'SC, tanah keras',
    mockMetricPga: 'PGA',
    mockMetricPgaSub: 'akselerasi puncak',
    mockMetricFs: 'FS LIKUEFAKSI',
    mockMetricFsSub: 'stabil',
    mockMetricElev: 'ELEVASI',
    mockMetricElevSub: 'standar',
    mockSubscoresTitle: 'SUB-SKOR',
    mockReportTitle: 'Laporan Audit S.A.F.E',
    mockReportAddr: 'Jalan Diponegoro, Pahoman, Bandar Lampung',
    mockReportDownload: 'Unduh PDF',
    mockReportShare: 'Salin Tautan',
    mockStatusChip: 'SKENARIO',

    /* ── Rail lapisan ── */
    railEyebrow: 'Lapisan Analisis',
    railTitle: 'Lima bahaya, satu kertas kerja',
    railLead:
      'Setiap audit memeriksa lima keluarga bahaya terhadap data spasial resmi. Hasilnya dirangkum jadi satu skor plus parameter teknis yang bisa Anda sitasi.',
    railPrev: 'Lapisan sebelumnya',
    railNext: 'Lapisan berikutnya',
    railGoTo: 'Ke lapisan',
    railSeismicTitle: 'Gempa',
    railSeismicDesc:
      'PGA desain dari PuSGeN, kedekatan sesar aktif, dan konteks megathrust. Semuanya dihitung dari katalog resmi, bukan perkiraan kasar.',
    railFloodTitle: 'Banjir',
    railFloodDesc:
      'Elevasi mdpl, jarak ke sungai/pantai, dan curah hujan dari Open-Meteo dirangkum menjadi label risiko banjir wilayah.',
    railLiquefactionTitle: 'Likuefaksi',
    railLiquefactionDesc:
      'Factor of Safety metode Seed & Idriss berbasis estimasi Vs30, lengkap dengan status yang menyebut kapan hasilnya perlu uji lab.',
    railVolcanicTitle: 'Vulkanik',
    railVolcanicDesc:
      'Pencocokan koordinat dengan Kawasan Rawan Bencana (KRB) PVMBG dan jarak ke gunung api aktif terdekat.',
    railTerrainTitle: 'Terrain',
    railTerrainDesc:
      'Kemiringan lereng, konteks longsor, dan penurunan lahan dari data topografi dan OpenStreetMap.',
    railSeismicReadLabel: 'PGA desain',
    railSeismicReadValue: '0,42 g',
    railFloodReadLabel: 'Elevasi tapak',
    railFloodReadValue: '91 mdpl',
    railLiquefactionReadLabel: 'FS likuefaksi',
    railLiquefactionReadValue: '2,00 · stabil',
    railVolcanicReadLabel: 'Radius KRB',
    railVolcanicReadValue: '18,7 km',
    railTerrainReadLabel: 'Kemiringan',
    railTerrainReadValue: '4,2°',
    railDemoBadge: 'Demo',
    railSeismicSteps: ['Katalog PuSGeN diunduh', 'PGA desain dihitung', '0,42 g siap kutip'],
    railFloodSteps: ['Elevasi & curah hujan ditarik', 'Model banjir wilayah', 'Label risiko 91 mdpl'],
    railLiquefactionSteps: ['Vs30 diestimasi', 'FS Seed & Idriss', '2,00 stabil tanpa lab'],
    railVolcanicSteps: ['KRB PVMBG dicocokkan', 'Jarak gunung dihitung', '18,7 km dari KRB'],
    railTerrainSteps: ['SRTM & OSM ditarik', 'Kemiringan dianalisis', '4,2° tercatat'],

    /* ── Misi ── */
    missionEyebrow: 'Kenapa ada',
    missionTitle: 'Lima portal pemerintah, satu berkas PBG',
    missionLead: 'Lima sumber resmi masuk, satu laporan SNI keluar — tanpa menyalin angka manual.',
    missionCardTitle: 'Laporan SNI 1726:2019',
    missionCardFoot: 'Setiap angka membawa sumbernya',
    missionSourcesLabel: 'Lima sumber resmi masuk',
    missionStampText: 'Teraudit',
    missionEngine: 'Mesin hitung SNI',
    missionReadyTag: 'Siap PBG',
    missionStatusHead: 'Status kelayakan',
    missionStatusOk: 'Memenuhi standar SNI 1726:2019',
    missionManual: '0 ketik manual',
    missionEngineSub: 'Deterministik · bukan tebakan AI',
    missionOutputLabel: 'Satu berkas keluar',
    missionOldLabel: 'Cara lama',
    missionOldStat: '5 portal · 5 format',
    missionOldDesc: 'Buka portal satu per satu, salin angkanya manual ke berkas.',
    missionOldRisk: 'Satu salah ketik, berkas dikembalikan',
    missionNewLabel: 'Dengan S.A.F.E House',
    missionNewStat: '1 koordinat · 1 berkas',
    missionNewDesc: 'Koordinat masuk, parameter SNI dihitung deterministik, rujukan tersemat otomatis.',
    missionNewProof: '0 ketik manual · siap lampir PBG',
    missionSrcTagPusgen: 'Peta sumber gempa',
    missionSrcTagInarisk: 'Indeks multi-bahaya',
    missionSrcTagPvmbg: 'Zona KRB & sesar',
    missionSrcTagUsgs: 'Katalog gempa',
    missionSrcTagBmkg: 'Hujan & iklim',
    missionSrcMxPusgen: 'Ss 0,85 · S1 0,38 g',
    missionSrcMxInarisk: 'Grid 30 m · 5 bahaya',
    missionSrcMxPvmbg: 'Peta 1:50.000',
    missionSrcMxUsgs: 'M 4,0+ · 50 thn',
    missionSrcMxBmkg: 'Presipitasi maksimum',
    missionPgaLabel: 'PGA desain',
    missionPgaVal: '0,42 g',
    missionPgaSub: 'Spektrum MCEr SNI 1726:2019',
    missionPgaStatus: 'Terverifikasi',
    missionSiteLabel: 'Kelas situs & Vs30',
    missionSiteVal: 'SC · Vs30 450 m/s',
    missionSiteSub: 'Vs30 estimasi · PuSGeN',
    missionSiteStatus: 'Tercantum',
    missionFsLabel: 'FS likuefaksi',
    missionFsVal: '2,00 · stabil',
    missionFsSub: 'Seed & Idriss · SNI 8460:2017',
    missionFsStatus: 'Aman',
    missionFloodLabel: 'Banjir & elevasi tapak',
    missionFloodVal: 'Rendah · 91 mdpl',
    missionFloodSub: 'InaRISK BNPB · Open-Meteo',
    missionFloodStatus: 'Terkendali',
    missionQuote: 'Fisika tidak bisa dirundung. Setiap angka di laporan ini bisa dilacak balik ke rumus dan sumbernya.',
    missionQuoteSource: 'Prinsip desain S.A.F.E House',

    /* ── Use cases ── */
    casesEyebrow: 'Untuk siapa',
    casesTitle: 'Tiga pekerjaan, satu alat',
    casesLead: 'Dipakai di titik berbeda dalam alur kerja, dari screening awal sampai kelengkapan berkas.',
    casePlate: 'Arsip Tanah',
    caseReadoutSiteLabel: 'Kelas situs',
    caseReadoutSite: 'SC · Vs30 450 m/s',
    caseReadoutPgaLabel: 'PGA desain',
    caseReadoutPga: '0,42 g',
    caseReadoutScoreLabel: 'Skor audit',
    caseReadoutScore: '65 · SEDANG',
    caseReadoutVs30Label: 'Vs30',
    caseReadoutVs30: '450 m/s',
    caseReadoutFsLabel: 'FS likuefaksi',
    caseReadoutFs: '2,00 · aman',
    caseCompareChip: 'Mode banding lahan',
    casePbgTitle: 'Konsultan PBG',
    casePbgDesc:
      'Lengkapi parameter SNI 1726:2019 untuk berkas perizinan tanpa membuka lima portal. Sumber data tercantum di tiap angka.',
    casePbgLink: 'Mulai audit lokasi',
    casePbgImgAlt: 'Ilustrasi pekerjaan penyusunan berkas perizinan bangunan di atas meja kerja.',
    caseDeveloperTitle: 'Developer',
    caseDeveloperDesc:
      'Screening puluhan kandidat lahan dalam hitungan menit sebelum mengeluarkan biaya penyelidikan tanah yang jauh lebih besar.',
    caseDeveloperLink: 'Bandingkan dua lahan',
    caseDeveloperImgAlt: 'Pemandangan kawasan permukiman peri-urban Indonesia dari udara.',
    caseGeoteknikTitle: 'Konsultan geoteknik',
    caseGeoteknikDesc:
      'Mulai desk study dari data terstruktur, bukan dari nol. Waktu lapangan jadi fokus ke titik yang benar-benar mencurigakan.',
    caseGeoteknikLink: 'Lihat halaman validasi',
    caseGeoteknikImgAlt: 'Detail permukaan tanah dan kontur wilayah Indonesia.',

    /* ── Metodologi ── */
    methodEyebrow: 'Metodologi',
    methodQuote: 'Perhitungan yang sama, masukan yang sama, hasil yang sama. Setiap kali.',
    methodSupport:
      'Semua angka dihitung deterministik dari rumus terstandar (SNI 1726:2019, Seed & Idriss) di atas data publik resmi. Tidak ada angka yang dihasilkan model bahasa. Lapisan AI hanya menjelaskan hasil, dan halaman validasi kami mendokumentasikan pembandingannya terhadap sumber publik.',
    methodCta: 'Lihat dokumentasi validasi',

    /* ── Showcase ── */
    showcaseEyebrow: 'Hasil audit',
    showcaseTitle: 'Satu layar, seluruh bukti',
    showcaseLead:
      'Contoh nyata hasil audit di Bandar Lampung: skor, parameter teknis, peta bahaya, dan jejak sumber dalam satu tampilan yang bisa dibaca klien maupun rekan insinyur.',
    showcaseWindowTitle: 'Hasil audit · Bandar Lampung',
    showcaseImgAlt:
      'Tangkapan layar hasil audit S.A.F.E House untuk Bandar Lampung: skor 65 SEDANG, PGA 0,42 g, kelas situs SC, peta bahaya, dan daftar sumber data.',
    showcaseCaptionScenario: 'Skenario kurasi app: Bandar Lampung · 65 SEDANG',
    showcaseCaptionValues: 'PGA 0,42 g · Vs30 450 m/s (SC) · FS 2,00 · elevasi 91 mdpl',
    calloutScoreTag: 'SKOR',
    calloutScoreTitle: '65 SEDANG, "layak dengan catatan"',
    calloutVs30Tag: 'PARAMETER',
    calloutVs30Title: 'Kelas situs SC (tanah keras) · Vs30 450 m/s',
    calloutFloodTag: 'BAHAYA',
    calloutFloodTitle: 'Elevasi 91 mdpl · radar lima bahaya wilayah',
    calloutSourcesTag: 'JEJAK SUMBER',
    calloutSourcesTitle: 'Setiap angka membawa sumber datanya',

    /* ── Deep dive ── */
    deepTitle: 'Kemampuan analisis',
    deepSeismicEyebrow: 'Seismik',
    deepSeismicTitle: 'PGA desain dan kelas situs, siap kutip',
    deepSeismicDesc:
      'Engine menghitung percepatan tanah desain dari peta sumber PuSGeN, mengestimasi Vs30 untuk kelas situs SNI, dan mencatat jarak ke sesar aktif terdekat. Satuan dan acuannya konsisten dengan berkas perizinan.',
    deepSeismicWindowTitle: 'Panel parameter seismik',
    deepSeismicImgAlt:
      'Panel parameter seismik aplikasi: PGA desain, kelas situs SD, dan jarak sesar aktif terdekat.',
    deepSeismicPoint1Label: 'PGA 0,42 g',
    deepSeismicPoint1Text: 'akselerasi puncak. 0,504 g di permukaan setelah faktor kelas situs.',
    deepSeismicPoint2Label: 'Kelas situs SC (tanah keras)',
    deepSeismicPoint2Text: 'Vs30 450 m/s, dengan status sumber yang jujur.',
    deepSeismicPoint3Label: 'Radar lima bahaya',
    deepSeismicPoint3Text: 'seismik, likuefaksi, banjir, longsor, dan penurunan lahan dalam satu pandangan.',
    deepLiquefactionEyebrow: 'Likuefaksi',
    deepLiquefactionTitle: 'FS likuefaksi dengan batas yang jujur',
    deepLiquefactionDesc:
      'Factor of Safety dihitung asinkron dengan metode Seed & Idriss di atas estimasi Vs30. Saat FS tipis (di atas 1 tapi dekat), laporan menyebutnya "waspada", bukan aman penuh, dan menandai uji laboratorium sebagai langkah lanjutan.',
    deepLiquefactionWindowTitle: 'Panel analisis likuefaksi',
    deepLiquefactionImgAlt:
      'Panel analisis likuefaksi aplikasi: nilai FS 2,00 berstatus stabil dan rekomendasi tindak lanjut bila data berubah.',
    deepLiquefactionPoint1Label: 'FS 2,00, stabil',
    deepLiquefactionPoint1Text: 'berlaku pada skenario kurasi ini. Status berubah otomatis bila FS tipis.',
    deepLiquefactionPoint2Label: 'Seed & Idriss',
    deepLiquefactionPoint2Text: 'metode standar, dihitung di server, bukan di browser.',
    deepLiquefactionPoint3Label: 'Batas jelas',
    deepLiquefactionPoint3Text: 'estimasi Vs30 bukan pengganti uji SPT/CPT laboratorium.',

    /* ── Sumber data ── */
    sourcesEyebrow: 'Sumber data',
    sourcesTitle: 'Ditarik dari yang resmi, dihitung di server',
    sourcesLead:
      'S.A.F.E House hanya membaca data publik resmi, dan memisahkan dengan jelas apa yang ditarik, apa yang dihitung, apa yang dijelaskan AI, dan apa yang tetap butuh verifikasi lapangan.',
    sourcesRolePull: 'Ditarik dari sumber resmi',
    sourcesRoleCompute: 'Dihitung deterministik',
    sourcesRoleAi: 'Dijelaskan AI',
    sourcesRoleField: 'Butuh lapangan',
    sourcesRoleComputeDesc:
      'Kelas situs, PGA desain, FS likuefaksi, dan skor agregat dihitung dari rumus terstandar. Hasilnya bisa direproduksi tanpa campuran model bahasa.',
    sourcesRoleAiDesc:
      'Lapisan AI hanya menyusun penjelasan naratif di atas angka yang sudah jadi. Ia tidak pernah mengubah skor, FS, Vs30, atau kelas bahaya.',
    sourcesRoleFieldDesc:
      'Uji penetrasi (SPT/CPT), desain fondasi rinci, dan SLF tetap ranah insinyur berlisensi. Laporan screening ini mendukung pekerjaan mereka, bukan menggantikannya.',
    sourcesPusgenName: 'PuSGeN 2024',
    sourcesPusgenOfficial: 'Publikasi resmi · diakses via InaRISK BNPB',
    sourcesPusgenDesc: 'Peta sumber dan geometri sesar gempa nasional, acuan perhitungan PGA.',
    sourcesInariskName: 'InaRISK BNPB',
    sourcesInariskOfficial: 'Badan Nasional Penanggulangan Bencana · LIVE',
    sourcesInariskDesc: 'Bahaya banjir, kerentanan spasial, dan geometri sesar PuSGeN 2024, ditarik langsung.',
    sourcesBmkgName: 'PuSGeN / BMKG',
    sourcesBmkgOfficial: 'Kerangka acuan parameter seismik nasional',
    sourcesBmkgDesc: 'Parameter SNI 1726:2019 mengacu kerangka ini, bukan feed live. Nilainya dihitung dari geometri sumber gempa.',
    sourcesUsgsName: 'USGS',
    sourcesUsgsOfficial: 'United States Geological Survey',
    sourcesUsgsDesc: 'Katalog kegempaan historis regional untuk konteks seismisitas.',
    sourcesPvmbgName: 'Zonasi KRB',
    sourcesPvmbgOfficial: 'Kerangka acuan zonasi vulkanik PVMBG',
    sourcesPvmbgDesc: 'Konteks Kawasan Rawan Bencana sebagai acuan, bukan feed live.',
    sourcesBigName: 'BIG',
    sourcesBigOfficial: 'Badan Informasi Geospasial',
    sourcesBigOfficialDesc: '',
    sourcesBigDesc: 'Data geospasial dasar Indonesia untuk konteks topografi.',
    sourcesOpenmeteoName: 'Open-Meteo',
    sourcesOpenmeteoOfficial: 'Layanan data iklim terbuka',
    sourcesOpenmeteoDesc: 'Curah hujan harian dan elevasi titik untuk analisis banjir.',
    sourcesOsmName: 'OpenStreetMap',
    sourcesOsmOfficial: 'Kontributor OpenStreetMap · Nominatim',
    sourcesOsmDesc: 'Objek lingkungan, geokoding alamat, dan konteks permukiman.',
    sourcesCaption: 'Pesisir Lampung, lanskap yang dianalisis, bukan sekadar latar.',

    /* ── Pipeline ── */
    pipelineEyebrow: 'Cara kerja',
    pipelineTitle: 'Dari koordinat ke laporan, dalam lima langkah',
    pipelineLead:
      'Alurnya sama untuk setiap titik: transparan, bisa diulang, dan tiap tahap meninggalkan jejak yang bisa diperiksa.',
    pipelineInputTitle: 'Koordinat masuk',
    pipelineInputDesc: 'Klik peta, ketik GPS, atau tempel tautan Google Maps.',
    pipelineFetchTitle: 'Penarikan data',
    pipelineFetchDesc: 'Sumber resmi diambil paralel: InaRISK, PuSGeN, USGS, Open-Meteo, OSM.',
    pipelineComputeTitle: 'Hitung deterministik',
    pipelineComputeDesc: 'Rumus SNI 1726:2019 dan Seed & Idriss dijalankan di server.',
    pipelineAiTitle: 'Penjelasan AI',
    pipelineAiDesc: 'Model menyusun narasi di atas angka tanpa menyentuh satu angka pun.',
    pipelineReportTitle: 'Laporan siap lampir',
    pipelineReportDesc: 'Skor, parameter, peta bahaya, dan sumber dalam satu dokumen.',
    pipelineNote:
      'Setiap audit adalah desk study berbasis data publik. Ia mempercepat pekerjaan Anda, sementara keputusan teknis akhir tetap di tangan insinyur berlisensi.',

    /* ── Sample report ── */
    reportEyebrow: 'Contoh laporan',
    reportTitle: 'Baca dulu, sebelum percaya',
    reportLead:
      'Pratinjau laporan untuk Bandar Lampung, dengan struktur yang sama seperti yang Anda terima setelah audit. Perhatikan pemisahan antara data ditarik, dihitung, dijelaskan AI, dan yang butuh lapangan.',
    reportTablistLabel: 'Bagian laporan',
    reportTabSummary: 'Ringkasan',
    reportTabParams: 'Parameter',
    reportTabSpatial: 'Bukti spasial',
    reportTabMethod: 'Sumber & metode',
    reportWindowTitle: 'Laporan screening · Bandar Lampung',
    reportRolePulled: 'Ditarik',
    reportRolePulledDesc: 'Data mentah dari sumber resmi, lengkap dengan atribusinya.',
    reportRoleComputed: 'Dihitung',
    reportRoleComputedDesc: 'Hasil rumus terstandar yang bisa direproduksi ulang.',
    reportRoleAi: 'Dijelaskan AI',
    reportRoleAiDesc: 'Narasi penjelas; tidak pernah mengubah angka.',
    reportRoleField: 'Lapangan',
    reportRoleFieldDesc: 'Yang tetap harus diverifikasi insinyur di lokasi.',
    reportSummaryIdLabel: 'LAPORAN SCREENING · CONTOH KURASI',
    reportSummaryLocation: 'Jalan Diponegoro, Pahoman, Bandar Lampung',
    reportSummaryCoord: '−5,4292 · 105,2610 · elevasi 94 mdpl',
    reportSummaryScore: '65',
    reportSummaryBand: 'SEDANG · LAYAK DENGAN CATATAN',
    reportSummaryText:
      'Lokasi berada dalam band risiko sedang. Guncangan tanah puncak 0,42 g jadi pencatat utama, sementara likuefaksi (FS 2,00, stabil) dan konteks tanah relatif terkendali. Layak dilanjutkan dengan catatan verifikasi geoteknik terarah.',
    reportAiBadge: 'S.A.F.E AI EXPERT',
    reportAiTitle: 'Rangkuman & Opini Ahli Geoteknik S.A.F.E AI',
    reportAiNarrative:
      'Berdasarkan sintesis multi-parameter geoteknik deterministik, lokasi Jalan Diponegoro (Pahoman) diklasifikasikan pada Kelas Situs SC (Tanah Keras) dengan percepatan puncak tanah dasar PGA = 0,42 g (PGA permukaan 0,504 g). Lapisan tanah memperlihatkan Faktor Keamanan Likuefaksi FS = 2,00 (Stabil, di atas batas kritis 1,20 metode Seed & Idriss). Potensi banjir permukaan terkendali pada elevasi 94 mdpl.',
    reportAiPoint1: 'Fondasi Dangkal/Rakit Layak: Kapasitas dukung tanah memadai untuk beban 1–2 lantai, wajib penulangan tahan gempa SNI 1726:2019.',
    reportAiPoint2: 'Risiko Likuefaksi Nihil: Nilai FS = 2,00 memastikan tidak diperlukan perbaikan tanah (soil improvement) skala besar.',
    reportAiPoint3: 'Kesiapan Dokumen PBG: Parameter PGA & Vs30 terverifikasi siap dilampirkan langsung pada berkas Persetujuan Bangunan Gedung.',
    reportSummaryPoint1: 'PGA 0,42 g. Di permukaan jadi 0,504 g setelah faktor kelas situs (1,20).',
    reportSummaryPoint2: 'Kelas situs SC (tanah keras), Vs30 450 m/s.',
    reportSummaryPoint3: 'FS likuefaksi 2,00, stabil pada skenario ini.',
    reportSummaryPoint4: 'Radar lima bahaya: seismik 40 · banjir 61 · tanah 10 · longsor 33.',
    reportParamVs30Value: '450 m/s',
    reportParamVs30Class: 'SC',
    reportParamVs30Note: 'Tanah keras; konfirmasi dengan uji geolistrik/SPT untuk desain final.',
    reportParamPgaLabel: 'PGA',
    reportParamPgaValue: '0,42 g',
    reportParamPgaNote: 'Akselerasi tanah puncak dari peta sumber gempa PuSGeN, acuan SNI 1726:2019.',
    reportParamFsValue: '2,00',
    reportParamFsNote: 'Seed & Idriss, berstatus stabil. Laporan otomatis menandai "waspada" bila FS tipis.',
    reportParamFloodLabel: 'Konteks banjir',
    reportParamFloodValue: 'SUB-SKOR 61',
    reportParamFloodNote: 'Elevasi 94 mdpl (standar). Banjir adalah satu dari lima bahaya yang dipetakan.',
    reportParamsFootnote: 'Angka pada contoh ini konsisten di seluruh halaman. Audit nyata menghitung ulang semuanya untuk koordinat Anda.',
    reportSpatialImgAlt: 'Peta bahaya spasial sekitar titik audit Bandar Lampung.',
    reportSpatial1Tag: 'SESMIK',
    reportSpatial1Text: 'Kedekatan sesar dan peta guncangan menunjukkan paparan tinggi di titik ini.',
    reportSpatial2Tag: 'BANJIR',
    reportSpatial2Text: 'Konteks drainase wilayah menempatkan lokasi pada band sedang.',
    reportSpatial3Tag: 'TERRAIN',
    reportSpatial3Text: 'Kemiringan lereng rendah; konteks longsor dan penurunan lahan tergolong rendah.',
    reportMethodPulledLabel: 'DATA DITARIK DARI',
    reportMethodLimitsLabel: 'BATASAN YANG DICANTUMKAN',
    reportMethodSource1: 'PuSGeN: peta sumber dan bahaya gempa',
    reportMethodSource2: 'InaRISK BNPB: bahaya banjir & kerentanan spasial',
    reportMethodSource3: 'USGS: katalog gempa historis',
    reportMethodSource4: 'Open-Meteo & OpenStreetMap: hujan, elevasi, objek lingkungan',
    reportMethodLimit1: 'Bukan pengganti uji tanah laboratorium (SPT/CPT).',
    reportMethodLimit2: 'Vs30 adalah estimasi model, bukan pengukuran langsung.',
    reportMethodLimit3: 'Keputusan desain fondasi tetap milik insinyur berlisensi.',
    reportMethodFootnote:
      'Laporan menyatakan dengan jelas bagian mana yang ditarik, dihitung, dijelaskan AI, dan yang membutuhkan verifikasi profesional.',

    /* ── FAQ ── */
    faqEyebrow: 'FAQ',
    faqTitle: 'Pertanyaan yang wajar untuk ditanyakan',
    faqLead: 'Jawaban singkat soal data, metode, dan batasan. Tanpa basa-basi pemasaran.',
    faqQ1: 'Apa itu S.A.F.E House?',
    faqA1:
      'S.A.F.E House (Seismic Analysis for Foundation Evaluation) mengubah satu koordinat menjadi parameter SNI 1726:2019 yang dibutuhkan berkas perizinan: kelas situs, PGA desain, FS likuefaksi, dan paparan bahaya banjir. Semuanya disusun jadi satu laporan screening yang bisa dilampirkan.',
    faqQ2: 'Dari mana datanya berasal?',
    faqA2:
      'Dari sumber publik resmi: PuSGeN dan BMKG (seismik), InaRISK BNPB (banjir & kerentanan), PVMBG (KRB & sesar aktif), USGS (katalog gempa), Open-Meteo (hujan & elevasi), serta OpenStreetMap/BIG untuk konteks geospasial. Setiap angka di laporan mencantumkan sumbernya.',
    faqQ3: 'Apakah hasilnya bisa dipertanggungjawabkan?',
    faqA3:
      'Semua angka dihitung deterministik dari rumus terstandar (SNI 1726:2019, Seed & Idriss) di atas data resmi. Masukan yang sama akan selalu menghasilkan keluaran yang sama. Halaman validasi kami mendokumentasikan pembandingan terbuka terhadap sumber publik.',
    faqQ4: 'Apa peran AI di dalamnya?',
    faqA4:
      'AI hanya menyusun penjelasan naratif di atas hasil perhitungan. Ia tidak pernah menghitung atau mengubah skor, FS, Vs30, PGA, maupun kelas bahaya. Perhitungan fisikanya sepenuhnya deterministik di server.',
    faqQ5: 'Apakah ini menggantikan uji tanah?',
    faqA5:
      'Tidak. Ini desk study berbasis data publik untuk screening cepat. Uji penetrasi (SPT/CPT), desain fondasi rinci, dan SLF tetap membutuhkan penyelidikan lapangan dan insinyur geoteknik berlisensi.',
    faqQ6: 'Apakah pencarian lokasi saya tersimpan?',
    faqA6:
      'Riwayat koordinat Anda disimpan lokal di peramban (localStorage) dan tidak dikirim ke server kami, kecuali Anda sengaja membagikan tautan laporan.',

    /* ── Testimoni pelaku industri ── */
    tstEyebrow: 'Dari lapangan',
    tstTitle: 'Dipakai di meja kerja yang menentukan.',
    tstLead:
      'Cara pelaku industri memakai S.A.F.E House dalam alur kerjanya — sebelum tanah dibeli, sebelum berkas diajukan, sebelum pondasi ditawarkan.',
    tstQuoteDeveloper:
      'Sebelum beli lahan, saya tempel koordinatnya dulu. Lima menit saya sudah tahu kandidat mana yang layak ditinjau lebih lanjut — dan mana yang sebaiknya dilewat.',
    tstNameDeveloper: 'Rendra Wijaya',
    tstRoleDeveloper: 'Developer properti, Jakarta',
    tstQuoteKontraktor:
      'Tiga puluh tahun di lapangan mengajari saya satu hal: jangan pernah menawarkan pondasi sebelum tahu risiko likuefasinya. Sekarang cek itu selesai dua menit sebelum survei dijadwalkan.',
    tstNameKontraktor: 'Ir. Bagus Prakoso',
    tstRoleKontraktor: 'Kontraktor fondasi, Surabaya',
    tstQuoteGeoteknik:
      'Saya memakainya sebagai first-pass desk study sebelum menyusun rencana penyelidikan tanah. Kalau FS likuefasinya rendah, prioritas bor sondir menjadi jelas sejak awal.',
    tstNameGeoteknik: 'Ir. Hartono Subagio, M.T.',
    tstRoleGeoteknik: 'Konsultan geoteknik, Yogyakarta',

    /* ── CTA ── */
    ctaEyebrow: 'Mulai',
    ctaTitle: 'Cukup satu alamat, parameter SNI siap lampir',
    ctaSub:
      'Masukkan alamat properti atau nama lokasi. Audit dihitung otomatis dari data resmi pemerintah, gratis tanpa perlu mendaftar.',
    ctaInputLabel: 'Alamat properti atau lokasi lahan',
    ctaPlaceholder: 'Contoh: Jalan Diponegoro, Pahoman, Bandar Lampung atau koordinat',
    ctaPlaceholderShort: 'Ketik alamat properti atau lokasi…',
    ctaSubmit: 'Analisis Sekarang',
    ctaError: 'Format tidak dikenali. Masukkan alamat properti, koordinat "lat, lon", atau tautan Google Maps.',
    ctaExample: 'Coba alamat contoh: Jalan Diponegoro, Pahoman, Bandar Lampung',
    ctaNote: 'Gratis · tanpa akun · sumber data tercantum',

    /* ── Footer ── */
    footerColProduct: 'Produk',
    footerColEvidence: 'Bukti & metode',
    footerStart: 'Mulai analisis',
    footerSampleReport: 'Contoh laporan',
    footerValidation: 'Halaman validasi',
    footerPipeline: 'Cara kerja',
    footerDesc:
      'Desk study geoteknik berbasis alamat properti: kelas situs, PGA desain, FS likuefaksi, dan bahaya banjir sesuai SNI 1726:2019.',
    footerContest: 'Building Indonesia by Emergent',
    footerDisclaimer:
      'Laporan screening, bukan pengganti penyelidikan tanah atau pendapat insinyur geoteknik berlisensi.',
  },

  en: {
    /* ── Nav ── */
    navLayers: 'Inside the app',
    navShowcase: 'Showcase',
    navValidation: 'Validation',
    navMethod: 'Methodology',
    navSources: 'Data Sources',
    navFaq: 'FAQ',
    navLangGroup: 'Language',
    navThemeToLight: 'Switch to light mode',
    navThemeToDark: 'Switch to dark mode',
    navCta: 'Start Analysis',

    /* ── Hero ── */
    heroBadgeTag: 'SNI STANDARD',
    heroBadge: 'Geotechnical Desk Study 1726:2019',
    heroBadgeLink: 'See how it works',
    heroTitlePrefix: 'Check property soil risk',
    heroTitleItalic: 'straight from the address',
    heroSub:
      'Type a property address. S.A.F.E House computes earthquake, liquefaction, and flood risk per SNI 1726:2019 from official BNPB, PuSGeN, and USGS data. Free, no account, done in two minutes.',
    heroCTA: 'Analyze for Free',
    heroKicker: 'Geotechnical desk study · SNI 1726:2019',
    heroFieldLabel: 'Property address, coordinates, or Google Maps link',
    heroFieldPlaceholder: 'Property address or coordinates',
    heroFieldSubmit: 'Analyze',
    heroFieldHint: 'Enter',
    heroReadoutIdle: 'Waiting for an address',
    heroReadoutAddress: 'Address · pick the point on the map',
    heroReadoutPreset: 'Sample location',
    heroReadoutCoord: 'Valid coordinates',
    heroReadoutInvalid: 'Coordinates out of range',
    heroExamplesLabel: 'Examples',
    heroDemoCta: 'See an example address',
    heroTrust: 'InaRISK BNPB · PuSGeN · BMKG · USGS · Open-Meteo · OpenStreetMap',
    heroWindowTitle: 'S.A.F.E House · /app · Bandar Lampung',
    heroAppAlt:
      'Interactive mockup of the S.A.F.E House app: Bandar Lampung map with an audit pin, a run-audit button, and a result panel showing score 65, category MODERATE.',
    heroCaptionRoute: 'Route /app · curated Bandar Lampung scenario',
    heroCaptionData: 'Data: official public sources · deterministic computation',

    /* ── Rail ── */
    heroProof1: '5 hazards analyzed',
    heroProof2: 'Official sources cited',
    heroProof3: 'Permit-file ready',

    /* ── Bento: Inside the app ── */
    bentoEyebrow: 'Inside the app',
    bentoTitle: 'Everything you need, one screen.',
    bentoLead:
      'No long feature lists. This is what happens every time an audit runs.',
    bentoMapTitle: 'Precise Map & Location.',
    bentoMapText: 'Official high-resolution tiles with an exact pin right on the analyzed property address.',
    bentoInputTitle: 'Type address, done.',
    bentoInputText: 'Simply enter a street name, property address, or project site. No account, no setup.',
    bentoReportTitle: 'SNI report.',
    bentoReportText: 'Permit-ready parameters with a source trail on every number.',
    bentoPipelineTitle: 'Fully automatic.',
    bentoPipelineText: 'Fetch, compute, score. Two minutes, repeatable.',
    bentoLayersTitle: 'Five hazards.',
    bentoLayersText: 'Seismic, liquefaction, flood, landslide, volcanic in one score.',
    bentoCta: 'Open app',

    /* ── Interactive /app mockup ── */
    mockNavMap: 'Map',
    mockNavResult: 'Results',
    mockNavReport: 'Report',
    mockLayersTitle: 'Hazard layers',
    mockPointsTitle: 'Audit points',
    mockPointsHint: 'Click the map to audit a new spot.',
    mockKlikHint: 'Click anywhere to audit',
    mockLayerSeismic: 'Seismic',
    mockLayerLiquefaction: 'Liquefaction',
    mockLayerFlood: 'Flood',
    mockLayerLandslide: 'Landslide',
    mockLayerVolcanic: 'Volcanic',
    mockCoordChip: '-5.4292, 105.2610',
    mockCityLabel: 'Bandar Lampung',
    mockBayLabel: 'Lampung Bay',
    mockRunAudit: 'Run Audit',
    mockRerun: 'Re-run Audit',
    mockStep1: 'Fetching official data',
    mockStep2: 'Computing SNI parameters',
    mockStep3: 'Composing score',
    mockScoreLabel: 'S.A.F.E SCORE',
    mockBandModerate: 'MODERATE',
    mockScoreNote: 'Viable to proceed with notes',
    mockMetricVs30: 'VS30',
    mockMetricVs30Sub: 'SC, stiff soil',
    mockMetricPga: 'PGA',
    mockMetricPgaSub: 'peak acceleration',
    mockMetricFs: 'FS LIQUEFACTION',
    mockMetricFsSub: 'stable',
    mockMetricElev: 'ELEVATION',
    mockMetricElevSub: 'standard',
    mockSubscoresTitle: 'SUB-SCORES',
    mockReportTitle: 'S.A.F.E Audit Report',
    mockReportAddr: 'Jalan Diponegoro, Pahoman, Bandar Lampung',
    mockReportDownload: 'Download PDF',
    mockReportShare: 'Copy Link',
    mockStatusChip: 'SCENARIO',

railEyebrow: 'Analysis Layers',
    railTitle: 'Five hazards, one working paper',
    railLead:
      'Every audit checks five hazard families against official spatial data. The results roll up into one score plus technical parameters you can cite.',
    railPrev: 'Previous layer',
    railNext: 'Next layer',
    railGoTo: 'Go to layer',
    railSeismicTitle: 'Earthquake',
    railSeismicDesc:
      'Design PGA from PuSGeN, active-fault proximity, and megathrust context, all computed from official catalogs rather than rough guesses.',
    railFloodTitle: 'Flood',
    railFloodDesc:
      'Elevation, distance to rivers and coasts, and Open-Meteo rainfall summarized into a regional flood-risk label.',
    railLiquefactionTitle: 'Liquefaction',
    railLiquefactionDesc:
      'Seed & Idriss factor of safety on a Vs30 estimate, with an explicit status for when lab testing is required.',
    railVolcanicTitle: 'Volcanic',
    railVolcanicDesc:
      'Coordinate matching against PVMBG volcanic hazard zones (KRB) and distance to the nearest active volcano.',
    railTerrainTitle: 'Terrain',
    railTerrainDesc:
      'Slope, landslide context, and land subsidence from topographic data and OpenStreetMap.',
    railSeismicReadLabel: 'Design PGA',
    railSeismicReadValue: '0.42 g',
    railFloodReadLabel: 'Site elevation',
    railFloodReadValue: '91 m asl',
    railLiquefactionReadLabel: 'Liquefaction FS',
    railLiquefactionReadValue: '2.00 · stable',
    railVolcanicReadLabel: 'KRB radius',
    railVolcanicReadValue: '18.7 km',
    railTerrainReadLabel: 'Slope',
    railTerrainReadValue: '4.2°',
    railDemoBadge: 'Demo',
    railSeismicSteps: ['PuSGeN catalog pulled', 'Design PGA computed', '0.42 g ready to cite'],
    railFloodSteps: ['Elevation & rainfall pulled', 'Regional flood model', '91 m asl risk label'],
    railLiquefactionSteps: ['Vs30 estimated', 'Seed & Idriss FS', '2.00 stable, no lab'],
    railVolcanicSteps: ['PVMBG KRB matched', 'Volcano distance computed', '18.7 km from KRB'],
    railTerrainSteps: ['SRTM & OSM pulled', 'Slope analyzed', '4.2° recorded'],

    /* ── Mission ── */
    missionEyebrow: 'Why we exist',
    missionTitle: 'Five government portals, one permit file',
    missionLead: 'Five official sources in, one SNI report out — no manual number copying.',
    missionCardTitle: 'SNI 1726:2019 report',
    missionCardFoot: 'Every number carries its source',
    missionSourcesLabel: 'Five official sources in',
    missionStampText: 'Audited',
    missionEngine: 'SNI compute engine',
    missionReadyTag: 'Permit-ready',
    missionStatusHead: 'Compliance status',
    missionStatusOk: 'Meets SNI 1726:2019',
    missionManual: '0 manual entry',
    missionEngineSub: 'Deterministic · not an AI guess',
    missionOutputLabel: 'One file out',
    missionOldLabel: 'The old way',
    missionOldStat: '5 portals · 5 formats',
    missionOldDesc: 'Open each portal one by one, hand-copy the numbers into the file.',
    missionOldRisk: 'One typo sends the file back',
    missionNewLabel: 'With S.A.F.E House',
    missionNewStat: '1 coordinate · 1 file',
    missionNewDesc: 'Coordinate in, SNI parameters computed deterministically, citations attached automatically.',
    missionNewProof: '0 manual entry · ready for the PBG file',
    missionSrcTagPusgen: 'Seismic source map',
    missionSrcTagInarisk: 'Multi-hazard index',
    missionSrcTagPvmbg: 'KRB & fault zones',
    missionSrcTagUsgs: 'Quake catalogue',
    missionSrcTagBmkg: 'Rain & climate',
    missionSrcMxPusgen: 'Ss 0.85 · S1 0.38 g',
    missionSrcMxInarisk: '30 m grid · 5 hazards',
    missionSrcMxPvmbg: '1:50,000 map',
    missionSrcMxUsgs: 'M 4.0+ · 50 yr',
    missionSrcMxBmkg: 'Max precipitation',
    missionPgaLabel: 'Design PGA',
    missionPgaVal: '0.42 g',
    missionPgaSub: 'MCEr spectrum, SNI 1726:2019',
    missionPgaStatus: 'Verified',
    missionSiteLabel: 'Site class & Vs30',
    missionSiteVal: 'SC · Vs30 450 m/s',
    missionSiteSub: 'Estimated Vs30 · PuSGeN',
    missionSiteStatus: 'Cited',
    missionFsLabel: 'Liquefaction FS',
    missionFsVal: '2.00 · stable',
    missionFsSub: 'Seed & Idriss · SNI 8460:2017',
    missionFsStatus: 'Safe',
    missionFloodLabel: 'Flood & site elevation',
    missionFloodVal: 'Low · 91 m asl',
    missionFloodSub: 'InaRISK BNPB · Open-Meteo',
    missionFloodStatus: 'Managed',
    missionQuote: 'Physics does not negotiate. Every number in this report traces back to a formula and a source.',
    missionQuoteSource: 'S.A.F.E House design principle',

    /* ── Use cases ── */
    casesEyebrow: 'Who it is for',
    casesTitle: 'Three jobs, one tool',
    casesLead: 'Used at different points in the workflow, from early screening to file completeness.',
    casePlate: 'Land Dossier',
    caseReadoutSiteLabel: 'Site class',
    caseReadoutSite: 'SC · Vs30 450 m/s',
    caseReadoutPgaLabel: 'Design PGA',
    caseReadoutPga: '0.42 g',
    caseReadoutScoreLabel: 'Audit score',
    caseReadoutScore: '65 · MODERATE',
    caseReadoutVs30Label: 'Vs30',
    caseReadoutVs30: '450 m/s',
    caseReadoutFsLabel: 'Liquefaction FS',
    caseReadoutFs: '2.00 · safe',
    caseCompareChip: 'Parcel compare mode',
    casePbgTitle: 'Permit consultants',
    casePbgDesc:
      'Complete SNI 1726:2019 parameters for permit files without opening five portals. The data source is cited on every number.',
    casePbgLink: 'Start a location audit',
    casePbgImgAlt: 'Illustration of building-permit paperwork on a work desk.',
    caseDeveloperTitle: 'Developers',
    caseDeveloperDesc:
      'Screen dozens of candidate parcels in minutes before spending far more on geotechnical investigation.',
    caseDeveloperLink: 'Compare two parcels',
    caseDeveloperImgAlt: 'Aerial view of an Indonesian peri-urban settlement.',
    caseGeoteknikTitle: 'Geotechnical engineers',
    caseGeoteknikDesc:
      'Start the desk study from structured data instead of zero, then point field time at what actually looks suspicious.',
    caseGeoteknikLink: 'See the validation page',
    caseGeoteknikImgAlt: 'Close-up of soil surface and regional contours in Indonesia.',

    /* ── Methodology ── */
    methodEyebrow: 'Methodology',
    methodQuote: 'Same inputs, same computation, same result. Every time.',
    methodSupport:
      'Every number is computed deterministically from standard formulas (SNI 1726:2019, Seed & Idriss) over official public data. No number is produced by a language model. The AI layer only explains results, and our validation page documents the open comparison against public sources.',
    methodCta: 'See the validation documentation',

    /* ── Showcase ── */
    showcaseEyebrow: 'Audit result',
    showcaseTitle: 'One screen, all the evidence',
    showcaseLead:
      'A real audit result for Bandar Lampung: score, technical parameters, hazard map, and the source trail in one readable view for clients and fellow engineers.',
    showcaseWindowTitle: 'Audit result · Bandar Lampung',
    showcaseImgAlt:
      'Screenshot of a S.A.F.E House audit result for Bandar Lampung: score 65 MODERATE, PGA 0.42 g, site class SC, hazard map, and data sources.',
    showcaseCaptionScenario: 'App curated scenario: Bandar Lampung · 65 MODERATE',
    showcaseCaptionValues: 'PGA 0.42 g · Vs30 450 m/s (SC) · FS 2.00 · elevation 91 m',
    calloutScoreTag: 'SCORE',
    calloutScoreTitle: '65 MODERATE, "viable with notes"',
    calloutVs30Tag: 'PARAMETERS',
    calloutVs30Title: 'Site class SC (stiff soil) · Vs30 450 m/s',
    calloutFloodTag: 'HAZARD',
    calloutFloodTitle: 'Elevation 91 m · five-hazard regional radar',
    calloutSourcesTag: 'SOURCE TRAIL',
    calloutSourcesTitle: 'Every number carries its data source',

    /* ── Deep dive ── */
    deepTitle: 'Analysis capabilities',
    deepSeismicEyebrow: 'Seismic',
    deepSeismicTitle: 'Design PGA and site class, ready to cite',
    deepSeismicDesc:
      'The engine computes design ground acceleration from PuSGeN source maps, estimates Vs30 for the SNI site class, and records the distance to the nearest active fault. Units and references stay consistent with permit files.',
    deepSeismicWindowTitle: 'Seismic parameter panel',
    deepSeismicImgAlt:
      'App seismic parameter panel: design PGA, site class SD, and nearest active-fault distance.',
    deepSeismicPoint1Label: 'PGA 0.42 g',
    deepSeismicPoint1Text: 'peak acceleration. 0.504 g at the surface after the site factor.',
    deepSeismicPoint2Label: 'Site class SC (stiff soil)',
    deepSeismicPoint2Text: 'Vs30 450 m/s, with an honest source status.',
    deepSeismicPoint3Label: 'Five-hazard radar',
    deepSeismicPoint3Text: 'seismic, liquefaction, flood, landslide, and subsidence in one view.',
    deepLiquefactionEyebrow: 'Liquefaction',
    deepLiquefactionTitle: 'Liquefaction FS with honest limits',
    deepLiquefactionDesc:
      'The factor of safety is computed asynchronously with the Seed & Idriss method over a Vs30 estimate. When FS is thin (above 1 but close), the report calls it "caution" rather than fully safe, and flags laboratory testing as the next step.',
    deepLiquefactionWindowTitle: 'Liquefaction analysis panel',
    deepLiquefactionImgAlt:
      'App liquefaction analysis panel: FS 2.00 with a stable status and follow-up guidance when data changes.',
    deepLiquefactionPoint1Label: 'FS 2.00, stable',
    deepLiquefactionPoint1Text: 'true in this curated scenario. The status switches automatically when FS is thin.',
    deepLiquefactionPoint2Label: 'Seed & Idriss',
    deepLiquefactionPoint2Text: 'the standard method, computed server-side, not in the browser.',
    deepLiquefactionPoint3Label: 'Explicit limits',
    deepLiquefactionPoint3Text: 'a Vs30 estimate is not a substitute for SPT/CPT lab tests.',

    /* ── Sources ── */
    sourcesEyebrow: 'Data sources',
    sourcesTitle: 'Pulled from official sources, computed on the server',
    sourcesLead:
      'S.A.F.E House reads only official public data, and clearly separates what is retrieved, what is computed, what AI explains, and what still requires field verification.',
    sourcesRolePull: 'Retrieved from official sources',
    sourcesRoleCompute: 'Computed deterministically',
    sourcesRoleAi: 'Explained by AI',
    sourcesRoleField: 'Requires field work',
    sourcesRoleComputeDesc:
      'Site class, design PGA, liquefaction FS, and the aggregate score are computed from standard formulas. The results are reproducible with no language-model involvement.',
    sourcesRoleAiDesc:
      'The AI layer only composes narrative explanations over finished numbers. It never changes the score, FS, Vs30, or hazard classes.',
    sourcesRoleFieldDesc:
      'Penetration testing (SPT/CPT), detailed foundation design, and occupancy certification remain the domain of licensed engineers. This screening supports that work, it does not replace it.',
    sourcesPusgenName: 'PuSGeN 2024',
    sourcesPusgenOfficial: 'Official publication · accessed via InaRISK BNPB',
    sourcesPusgenDesc: 'National seismic source maps and fault geometry, the PGA reference.',
    sourcesInariskName: 'InaRISK BNPB',
    sourcesInariskOfficial: 'National Disaster Management Agency · LIVE',
    sourcesInariskDesc: 'Flood hazard, spatial vulnerability, and PuSGeN 2024 fault geometry, pulled directly.',
    sourcesBmkgName: 'PuSGeN / BMKG',
    sourcesBmkgOfficial: 'National seismic reference framework',
    sourcesBmkgDesc: 'SNI 1726:2019 parameters reference this framework rather than a live feed. Values are computed from source geometry.',
    sourcesUsgsName: 'USGS',
    sourcesUsgsOfficial: 'United States Geological Survey',
    sourcesUsgsDesc: 'Regional historical earthquake catalog for seismicity context.',
    sourcesPvmbgName: 'KRB zoning',
    sourcesPvmbgOfficial: 'PVMBG volcanic zoning reference',
    sourcesPvmbgDesc: 'Volcanic hazard zone (KRB) context as a reference, not a live feed.',
    sourcesBigName: 'BIG',
    sourcesBigOfficial: 'Geospatial Information Agency of Indonesia',
    sourcesBigDesc: 'Indonesian base geospatial data for topographic context.',
    sourcesOpenmeteoName: 'Open-Meteo',
    sourcesOpenmeteoOfficial: 'Open climate data service',
    sourcesOpenmeteoDesc: 'Daily rainfall and point elevation for flood analysis.',
    sourcesOsmName: 'OpenStreetMap',
    sourcesOsmOfficial: 'OpenStreetMap contributors · Nominatim',
    sourcesOsmDesc: 'Environment features, address geocoding, and settlement context.',
    sourcesCaption: 'The Lampung coast, a landscape being analyzed rather than just a backdrop.',

    /* ── Pipeline ── */
    pipelineEyebrow: 'How it works',
    pipelineTitle: 'From coordinate to report, in five steps',
    pipelineLead:
      'The flow is the same for every point: transparent, repeatable, and every step leaves a trail you can inspect.',
    pipelineInputTitle: 'Coordinate in',
    pipelineInputDesc: 'Click the map, type GPS coordinates, or paste a Google Maps link.',
    pipelineFetchTitle: 'Data retrieval',
    pipelineFetchDesc: 'Official sources fetched in parallel: InaRISK, PuSGeN, USGS, Open-Meteo, OSM.',
    pipelineComputeTitle: 'Deterministic computation',
    pipelineComputeDesc: 'SNI 1726:2019 and Seed & Idriss formulas run on the server.',
    pipelineAiTitle: 'AI explanation',
    pipelineAiDesc: 'A model composes the narrative over the numbers without touching one.',
    pipelineReportTitle: 'Report ready to attach',
    pipelineReportDesc: 'Score, parameters, hazard map, and sources in one document.',
    pipelineNote:
      'Every audit is a desk study over public data. It accelerates your work while final technical decisions stay with licensed engineers.',

    /* ── Sample report ── */
    reportEyebrow: 'Sample report',
    reportTitle: 'Read it before you trust it',
    reportLead:
      'A preview for Bandar Lampung with the same structure you receive after an audit. Note the separation between retrieved data, computed values, AI explanation, and what requires field work.',
    reportTablistLabel: 'Report sections',
    reportTabSummary: 'Summary',
    reportTabParams: 'Parameters',
    reportTabSpatial: 'Spatial evidence',
    reportTabMethod: 'Sources & method',
    reportWindowTitle: 'Screening report · Bandar Lampung',
    reportRolePulled: 'Retrieved',
    reportRolePulledDesc: 'Raw data from official sources, with attribution.',
    reportRoleComputed: 'Computed',
    reportRoleComputedDesc: 'Standard-formula results, fully reproducible.',
    reportRoleAi: 'Explained by AI',
    reportRoleAiDesc: 'Narrative explanation; never changes the numbers.',
    reportRoleField: 'Field',
    reportRoleFieldDesc: 'What an engineer must still verify on site.',
    reportSummaryIdLabel: 'SCREENING REPORT · CURATED SAMPLE',
    reportSummaryLocation: 'Jalan Diponegoro, Pahoman, Bandar Lampung',
    reportSummaryCoord: '−5.4292 · 105.2610 · elevation 94 m',
    reportSummaryScore: '65',
    reportSummaryBand: 'MODERATE · VIABLE WITH NOTES',
    reportSummaryText:
      'This location sits in a moderate risk band. Peak ground shaking of 0.42 g is the main flag, while liquefaction (FS 2.00, stable) and soil context are comparatively controlled. Viable to proceed with directed geotechnical verification.',
    reportAiBadge: 'S.A.F.E AI EXPERT',
    reportAiTitle: 'S.A.F.E AI Geotechnical Expert Synthesis & Narrative',
    reportAiNarrative:
      'Based on deterministic geotechnical parameter synthesis, the Jalan Diponegoro (Pahoman) parcel is classified as Site Class SC (Stiff Soil) with bedrock peak ground acceleration PGA = 0.42 g (surface PGA 0.504 g). The soil profile demonstrates a Liquefaction Safety Factor of FS = 2.00 (Stable, safely above the critical threshold of 1.20 under Seed & Idriss methodology). Surface flood risk is well-contained at 94 m elevation.',
    reportAiPoint1: 'Shallow / Mat Foundation Viable: Soil bearing capacity is sufficient for 1–2 story structures; standard SNI 1726:2019 seismic detailing is required.',
    reportAiPoint2: 'Zero Liquefaction Risk: FS = 2.00 confirms no major deep soil stabilization or ground improvement is needed.',
    reportAiPoint3: 'PBG Permit Ready: Verified PGA & Vs30 parameters can be directly attached to the building approval documentation.',
    reportSummaryPoint1: 'PGA 0.42 g. Surface PGA becomes 0.504 g after the site factor (1.20).',
    reportSummaryPoint2: 'Site class SC (stiff soil), Vs30 450 m/s.',
    reportSummaryPoint3: 'Liquefaction FS 2.00, stable in this scenario.',
    reportSummaryPoint4: 'Five-hazard radar: seismic 40 · flood 61 · soil 10 · landslide 33.',
    reportParamVs30Value: '450 m/s',
    reportParamVs30Class: 'SC',
    reportParamVs30Note: 'Stiff soil; confirm with geoelectric/SPT testing for final design.',
    reportParamPgaLabel: 'PGA',
    reportParamPgaValue: '0.42 g',
    reportParamPgaNote: 'Peak ground acceleration from PuSGeN seismic source maps, per SNI 1726:2019.',
    reportParamFsValue: '2.00',
    reportParamFsNote: 'Seed & Idriss with a stable status. The report automatically flags "caution" when FS is thin.',
    reportParamFloodLabel: 'Flood context',
    reportParamFloodValue: 'SUB-SCORE 61',
    reportParamFloodNote: 'Elevation 94 m (standard); flood is one of five mapped hazards.',
    reportParamsFootnote:
      'The numbers in this sample are the canonical scenario used consistently across the page. A real audit recomputes everything for your coordinate.',
    reportSpatialImgAlt: 'Spatial hazard map around the Bandar Lampung audit point.',
    reportSpatial1Tag: 'SEISMIC',
    reportSpatial1Text: 'Fault proximity and shaking maps show high exposure at this point.',
    reportSpatial2Tag: 'FLOOD',
    reportSpatial2Text: 'Regional drainage context places the parcel in the moderate band.',
    reportSpatial3Tag: 'TERRAIN',
    reportSpatial3Text: 'Low slope; landslide and subsidence context are low.',
    reportMethodPulledLabel: 'DATA RETRIEVED FROM',
    reportMethodLimitsLabel: 'STATED LIMITATIONS',
    reportMethodSource1: 'PuSGeN: seismic source and hazard maps',
    reportMethodSource2: 'InaRISK BNPB: flood hazard & spatial vulnerability',
    reportMethodSource3: 'USGS: historical earthquake catalog',
    reportMethodSource4: 'Open-Meteo & OpenStreetMap: rainfall, elevation, environment features',
    reportMethodLimit1: 'Not a substitute for laboratory soil testing (SPT/CPT).',
    reportMethodLimit2: 'Vs30 is a model estimate, not a direct measurement.',
    reportMethodLimit3: 'Foundation design decisions remain with licensed engineers.',
    reportMethodFootnote:
      'The report states clearly which parts are retrieved, computed, explained by AI, and which require professional verification.',

    /* ── FAQ ── */
    faqEyebrow: 'FAQ',
    faqTitle: 'Questions you should be asking',
    faqLead: 'Short answers about data, method, and limits. No marketing padding.',
    faqQ1: 'What is S.A.F.E House?',
    faqA1:
      'S.A.F.E House (Seismic Analysis for Foundation Evaluation) turns one coordinate into the SNI 1726:2019 parameters a permit file needs: site class, design PGA, liquefaction FS, and flood hazard exposure. All of it is assembled into one attachable screening report.',
    faqQ2: 'Where does the data come from?',
    faqA2:
      'From official public sources: PuSGeN and BMKG (seismic), InaRISK BNPB (flood & vulnerability), PVMBG (hazard zones & active faults), USGS (earthquake catalog), Open-Meteo (rainfall & elevation), plus OpenStreetMap/BIG for geospatial context. Every number in the report cites its source.',
    faqQ3: 'Can the results be defended?',
    faqA3:
      'Every number is computed deterministically from standard formulas (SNI 1726:2019, Seed & Idriss) over official data. The same inputs always produce the same result. Our validation page documents the open comparison against public sources.',
    faqQ4: 'What role does AI play?',
    faqA4:
      'AI only composes narrative explanations over computed results. It never calculates or changes the score, FS, Vs30, PGA, or hazard classes. The physics is fully deterministic and runs server-side.',
    faqQ5: 'Does this replace soil testing?',
    faqA5:
      'No. This is a public-data desk study for fast screening. Penetration testing (SPT/CPT), detailed foundation design, and occupancy certification still require field investigation and licensed geotechnical engineers.',
    faqQ6: 'Is my location history stored?',
    faqA6:
      'Your coordinate history is stored locally in your browser (localStorage) and is not sent to our servers for storage, unless you deliberately share a report link.',

    /* ── Testimoni pelaku industri ── */
    tstEyebrow: 'From the field',
    tstTitle: 'Used at the desks where decisions happen.',
    tstLead:
      'How industry practitioners use S.A.F.E House in their workflow — before land is bought, before permits are filed, before foundations are quoted.',
    tstQuoteDeveloper:
      'Before buying land, I paste the coordinates first. Within five minutes I know which candidates are worth a closer look — and which to pass on.',
    tstNameDeveloper: 'Rendra Wijaya',
    tstRoleDeveloper: 'Property developer, Jakarta',
    tstQuoteKontraktor:
      'Thirty years in the field taught me one thing: never quote a foundation before you know the liquefaction risk. That check now takes two minutes, before the survey is even scheduled.',
    tstNameKontraktor: 'Ir. Bagus Prakoso',
    tstRoleKontraktor: 'Foundation contractor, Surabaya',
    tstQuoteGeoteknik:
      'I use it as a first-pass desk study before planning the soil investigation. If the liquefaction FS comes back low, boring priorities are clear from day one.',
    tstNameGeoteknik: 'Ir. Hartono Subagio, M.T.',
    tstRoleGeoteknik: 'Geotechnical consultant, Yogyakarta',

    /* ── CTA ── */
    ctaEyebrow: 'Get started',
    ctaTitle: 'One address, two minutes, permit-ready parameters',
    ctaSub:
      'Enter any property address or location. The audit computes automatically from official sources, free with no account required.',
    ctaInputLabel: 'Property address or location',
    ctaPlaceholder: 'e.g. Jalan Diponegoro, Pahoman, Bandar Lampung or coordinates',
    ctaPlaceholderShort: 'Type property address or location…',
    ctaSubmit: 'Analyze Now',
    ctaError: 'Unrecognized format. Enter a property address, "lat, lon" coordinates, or a Google Maps link.',
    ctaExample: 'Try sample address: Jalan Diponegoro, Pahoman, Bandar Lampung',
    ctaNote: 'Free · no account · sources attached',

    /* ── Footer ── */
    footerColProduct: 'Product',
    footerColEvidence: 'Evidence & method',
    footerStart: 'Start an analysis',
    footerSampleReport: 'Sample report',
    footerValidation: 'Validation page',
    footerPipeline: 'How it works',
    footerDesc:
      'Geotechnical desk study from a property address: site class, design PGA, liquefaction FS, and flood hazard per SNI 1726:2019.',
    footerContest: 'Building Indonesia by Emergent',
    footerDisclaimer:
      'A screening report, not a substitute for soil investigation or a licensed geotechnical engineer\u2019s judgment.',
  },
};
